services:
  auth-api:
    build:
      context: .
      dockerfile: src/Services/Auth/Auth.Api/Dockerfile
    container_name: auth-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY}
    volumes:
      - ./logs/auth-api:/app/logs
    networks:
      - postgres_app-network

  meals-api:
    build:
      context: .
      dockerfile: src/Services/Meals/Meals.Api/Dockerfile
    container_name: meals-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY}
    volumes:
      - ./logs/meals-api:/app/logs
      - ./uploads/meals-api:/app/wwwroot/uploads
    networks:
      - postgres_app-network

  planner-api:
    build:
      context: .
      dockerfile: src/Services/Planner/Planner.Api/Dockerfile
    container_name: planner-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY}
    volumes:
      - ./logs/planner-api:/app/logs
    networks:
      - postgres_app-network

  api-gateway:
    build:
      context: .
      dockerfile: src/Gateway/ApiGateway/Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "80:8080"
    volumes:
      - ./logs/api-gateway:/app/logs
    depends_on:
      - auth-api
      - meals-api
      - planner-api
    networks:
      - postgres_app-network

networks:
  postgres_app-network:
    external: true
